@baseUrl = https://localhost:7164

### 🟢 GET - Listar todas as motos
GET {{baseUrl}}/api/Moto
Accept: application/json

### 🔵 POST - Criar uma nova moto
POST {{baseUrl}}/api/Moto
Content-Type: application/json

{
  "id": 1,
  "nome": "mottu",
  "tag": "alomottu2",
  "placa": 1236784
}

### 🟡 GET - Obter moto por ID
GET {{baseUrl}}/api/Moto/1
Accept: application/json

### 🟠 PUT - Atualizar moto por ID
PUT {{baseUrl}}/api/Moto/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Honda atualizado",
  "tag": "aloHonda123",
  "placa": 1234567
}

### 🔴 DELETE - Remover moto por ID
DELETE {{baseUrl}}/api/Moto/1
Accept: application/json

